### PR TITLE
v1.0.0

### PR DESCRIPTION
**Pull request by Yu-jinKim**
Initial release

---
This change is [Reviewable](https://reviewable.io/reviews/eastgenomics/dx_job_monitor/1)

### CODE REVIEW

**Review by jethror1 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/dx_job_monitor/1)* status: 0 of 3 files reviewed, 3 unresolved discussions (waiting on @jethror1 and @Yu-jinKim)

___
*[dx_job_monitor.py, line 69 at r1](https://reviewable.io/reviews/eastgenomics/dx_job_monitor/1#-MK5i-63AN3OHPuWOBVu:-MK5i-63AN3OHPuWOBVv:bjn6zno) ([raw file](https://github.com/eastgenomics/dx_job_monitor/blob/fc63edff3892f31020392a043e7205d349199dff/dx_job_monitor.py#L69)):*
> ```Python
> 
>     for project, jobs in project2jobs.items():
>         if jobs == []:
> ```

this could result in a lot of alerts every day, I think it would be better that it gave 1 for all those with no fails, then individual messages for fails
___
*[dx_job_monitor.py, line 85 at r1](https://reviewable.io/reviews/eastgenomics/dx_job_monitor/1#-MK5hcYX50521gWSLlfQ:-MK5hcYX50521gWSLlfR:bc1mc5c) ([raw file](https://github.com/eastgenomics/dx_job_monitor/blob/fc63edff3892f31020392a043e7205d349199dff/dx_job_monitor.py#L85)):*
> ```Python
> 
> if __name__ == "__main__":
>     main()
> ```

no new line at end
___
*[README.md, line 3 at r1](https://reviewable.io/reviews/eastgenomics/dx_job_monitor/1#-MK5kCjSEZ0425nRPOOK:-MK5kCjSEZ0425nRPOOL:b180p48) ([raw file](https://github.com/eastgenomics/dx_job_monitor/blob/fc63edff3892f31020392a043e7205d349199dff/README.md#L3)):*
> ```Markdown
> # dx_job_monitor
> Check if the 002 jobs completed correctly and sends notifications
> ```

also requires hermes,

**Review by Yu-jinKim — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/dx_job_monitor/1)* status: 0 of 3 files reviewed, 3 unresolved discussions (waiting on @jethror1)

___
*[dx_job_monitor.py, line 69 at r1](https://reviewable.io/reviews/eastgenomics/dx_job_monitor/1#-MK5i-63AN3OHPuWOBVu:-MK9oooz7vldMZMkNo4e:b-896fix) ([raw file](https://github.com/eastgenomics/dx_job_monitor/blob/fc63edff3892f31020392a043e7205d349199dff/dx_job_monitor.py#L69)):*
<details><summary><i>Previously, jethror1 wrote…</i></summary><blockquote>

this could result in a lot of alerts every day, I think it would be better that it gave 1 for all those with no fails, then individual messages for fails
</blockquote></details>

Done.
___
*[dx_job_monitor.py, line 85 at r1](https://reviewable.io/reviews/eastgenomics/dx_job_monitor/1#-MK5hcYX50521gWSLlfQ:-MK9opqV5gGxqJx57VFt:b-896fix) ([raw file](https://github.com/eastgenomics/dx_job_monitor/blob/fc63edff3892f31020392a043e7205d349199dff/dx_job_monitor.py#L85)):*
<details><summary><i>Previously, jethror1 wrote…</i></summary><blockquote>

no new line at end
</blockquote></details>

Done.
___
*[README.md, line 3 at r1](https://reviewable.io/reviews/eastgenomics/dx_job_monitor/1#-MK5kCjSEZ0425nRPOOK:-MKA6Ej10F4GmvH8txep:b-896fix) ([raw file](https://github.com/eastgenomics/dx_job_monitor/blob/fc63edff3892f31020392a043e7205d349199dff/README.md#L3)):*
<details><summary><i>Previously, jethror1 wrote…</i></summary><blockquote>

also requires hermes,
</blockquote></details>

Done.

**Review by jethror1 — CHANGES_REQUESTED** [review]
> Reviewed 1 of 3 files at r1.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/dx_job_monitor/1)* status: 1 of 3 files reviewed, 5 unresolved discussions (waiting on @jethror1 and @Yu-jinKim)

___
*[dx_job_monitor.py, line 18 at r2](https://reviewable.io/reviews/eastgenomics/dx_job_monitor/1#-MKAIERiEW2BzDQXGfA4:-MKAIERj2yPSO6Bsa90j:bwf08w5) ([raw file](https://github.com/eastgenomics/dx_job_monitor/blob/e92801fb7e4ed8496a670467290bab6883c543d6/dx_job_monitor.py#L18)):*
> ```Python
> import hermes
> 
> TOKEN_FILE_PATH = "../hermes/slack_token.txt"
> ```

need to specify in readme that slack token needs to be here
___
*[README.md, line 3 at r2](https://reviewable.io/reviews/eastgenomics/dx_job_monitor/1#-MKAH2jh6Ck_pzBRNmRF:-MKAH2jh6Ck_pzBRNmRG:b6n1o8p) ([raw file](https://github.com/eastgenomics/dx_job_monitor/blob/e92801fb7e4ed8496a670467290bab6883c543d6/README.md#L3)):*
> ```Markdown
> ## What does this app do?
> 
> Check if the 002 projects had jobs run and if any failed sending messages to egg-alerts if that is the case and egg-logs to inform the team of projects that had either no jobs run in the last 24h and no issues on jobs run in the last 24h.
> ```

that is confusing to read, better rephrased something like:

Checks for jobs run in any 002 project in the last 24 and sends notifications to Slack. 
If any jobs have failed in a project a message will be sent to egg-alerts, and those projects where all jobs completed successfully a message will be sent to egg-logs.
___
*[README.md, line 11 at r2](https://reviewable.io/reviews/eastgenomics/dx_job_monitor/1#-MKAGpWRELYVAfELn-x9:-MKAGpWRELYVAfELn-xA:blquxqs) ([raw file](https://github.com/eastgenomics/dx_job_monitor/blob/e92801fb7e4ed8496a670467290bab6883c543d6/README.md#L11)):*
> ```Markdown
> ## What data are required for this app to run?
> 
> This requires Hermes and the dnanexus_token file in the same folder as dx_job_monitor.py:
> ```

also requires slack token?
___
*[README.md, line 24 at r2](https://reviewable.io/reviews/eastgenomics/dx_job_monitor/1#-MKAGvTd3FAdEJvc__No:-MKAGvTd3FAdEJvc__Np:b-js42dh) ([raw file](https://github.com/eastgenomics/dx_job_monitor/blob/e92801fb7e4ed8496a670467290bab6883c543d6/README.md#L24)):*
> ```Markdown
> ## What does this app output?
> 
> A txt file called hermes.log logs all that is going on.
> ```

also outputs messages to respective slack channels

**Review by jethror1 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/dx_job_monitor/1)* status: 1 of 3 files reviewed, 5 unresolved discussions (waiting on @Yu-jinKim)

___
*[dx_job_monitor.py, line 85 at r3](https://reviewable.io/reviews/eastgenomics/dx_job_monitor/1#-MKAMMs96WVIW8g7a-wX:-MKAMMs96WVIW8g7a-wY:bwan9uw) ([raw file](https://github.com/eastgenomics/dx_job_monitor/blob/80d670516ad3789021513666e373c5770ed0b3b1/dx_job_monitor.py#L85)):*
> ```Python
>                 jobs = ", ".join(project2jobs[project][state])
> 
>                 if state == "failed":
> ```

if it fails to send a notificaiton here will it continue in the loop ? i.e. can there be a case where internet drops for a short period, it fails to send a message about a failed job, internet reconnects then it sends the notifcation of all runs with no fails? This would leave a state where it looks like it has run fine as there is an egg-logs notification but has missed sending an alert and would only be obvious through reading the logs
___
*[dx_job_monitor.py, line 97 at r3](https://reviewable.io/reviews/eastgenomics/dx_job_monitor/1#-MKALd466ych6XDKN84i:-MKALd466ych6XDKN84j:bic3ay) ([raw file](https://github.com/eastgenomics/dx_job_monitor/blob/80d670516ad3789021513666e373c5770ed0b3b1/dx_job_monitor.py#L97)):*
> ```Python
>                         }
>                     )
>         else:
> ```

what would happen if there were say 50 projects and it

**Review by Yu-jinKim — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/dx_job_monitor/1)* status: 1 of 3 files reviewed, 5 unresolved discussions (waiting on @jethror1 and @Yu-jinKim)

___
*[dx_job_monitor.py, line 85 at r3](https://reviewable.io/reviews/eastgenomics/dx_job_monitor/1#-MKAMMs96WVIW8g7a-wX:-MKAgDCOE3S3LBIj0QHU:bph27bb) ([raw file](https://github.com/eastgenomics/dx_job_monitor/blob/80d670516ad3789021513666e373c5770ed0b3b1/dx_job_monitor.py#L85)):*
<details><summary><i>Previously, jethror1 wrote…</i></summary><blockquote>

if it fails to send a notificaiton here will it continue in the loop ? i.e. can there be a case where internet drops for a short period, it fails to send a message about a failed job, internet reconnects then it sends the notifcation of all runs with no fails? This would leave a state where it looks like it has run fine as there is an egg-logs notification but has missed sending an alert and would only be obvious through reading the logs
</blockquote></details>

fail job: goes into hermes
tries to send message 5 times
if it fails 5 times it's going to sys.exit(-1)
so it should be fine

**Review by jethror1 — APPROVED** [review]
:lgtm:

> Reviewed 1 of 2 files at r3, 1 of 1 files at r4.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/dx_job_monitor/1#-:-MKAge4VE-sFmz5tL6VC:bnfp4nl)* status: all files reviewed, 4 unresolved discussions (waiting on @jethror1 and @Yu-jinKim)

**Review by jethror1 — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/eastgenomics/dx_job_monitor/1#-:-MKAgg7T8XTR--6LASsY:bnfp4nl)* status: all files reviewed, 3 unresolved discussions (waiting on @Yu-jinKim)

**Review by jethror1 — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/dx_job_monitor/1)* status: :shipit: complete! all files reviewed, all discussions resolved

___
*[README.md, line 3 at r2](https://reviewable.io/reviews/eastgenomics/dx_job_monitor/1#-MKAH2jh6Ck_pzBRNmRF:-MKAgpl5DjQ0LZW1dk-C:bb6un1j) ([raw file](https://github.com/eastgenomics/dx_job_monitor/blob/e92801fb7e4ed8496a670467290bab6883c543d6/README.md#L3)):*
<details><summary><i>Previously, jethror1 wrote…</i></summary><blockquote>

that is confusing to read, better rephrased something like:

Checks for jobs run in any 002 project in the last 24 and sends notifications to Slack. 
If any jobs have failed in a project a message will be sent to egg-alerts, and those projects where all jobs completed successfully a message will be sent to egg-logs.
</blockquote></details>

Done
___
*[README.md, line 24 at r2](https://reviewable.io/reviews/eastgenomics/dx_job_monitor/1#-MKAGvTd3FAdEJvc__No:-MKAgqap6MBdrnM2h0q7:bb6un1j) ([raw file](https://github.com/eastgenomics/dx_job_monitor/blob/e92801fb7e4ed8496a670467290bab6883c543d6/README.md#L24)):*
<details><summary><i>Previously, jethror1 wrote…</i></summary><blockquote>

also outputs messages to respective slack channels
</blockquote></details>

Done

**Pull request merged**
