### PR TITLE
Optimization

### PR DESCRIPTION
**Pull request by JasonLing95**
- upgrade dependencies in pip
- refactor some function into smaller functions
- #5 

Screenshot 2023-12-08 at 15 33 56

- - -
This change is [Reviewable](https://reviewable.io/reviews/eastgenomics/dx_job_monitor/6)

### CODE REVIEW

**Review by jethror1 — CHANGES_REQUESTED** [review]
> Reviewed 2 of 5 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/dx_job_monitor/6)* status: 2 of 5 files reviewed, 2 unresolved discussions (waiting on @JasonLing95)

___
*[`dx_job_monitor.py` line 142 at r1](https://reviewable.io/reviews/eastgenomics/dx_job_monitor/6#-Nl94-Qr7yEORNOOdfwo:-Nl94-Qr7yEORNOOdfwp:b-9o9h0h) ([raw file](https://github.com/eastgenomics/dx_job_monitor/blob/305ac6023d10d92b9837bb95528fec8757e6c742/dx_job_monitor.py#L142)):*
> ```Python
> 
>         if jobs:
>             project_name = _get_project_name(id)
> ```

instead of doing a query for project name for every project thats had jobs run, why don't we do a single query of dx find projects and then we can just look up the ID in this return dict to get the name? we already have a query outside of here to get all 002 projects, which should have the name in the response so could be passed here



_Code quote:_
```Python
project_name = _get_project_name(id)
```
___
*[`dx_job_monitor.py` line 150 at r1](https://reviewable.io/reviews/eastgenomics/dx_job_monitor/6#-Nl94RFt4Q0PZbdPaLcz:-Nl94RFt4Q0PZbdPaLd-:b-xx37fr) ([raw file](https://github.com/eastgenomics/dx_job_monitor/blob/305ac6023d10d92b9837bb95528fec8757e6c742/dx_job_monitor.py#L150)):*
> ```Python
> 
>             for job_id in jobs:
>                 job_description = _get_job_description(job_id)
> ```

again do we need to do this? can't all the details be included in _get_jobs_in_porject() if we specify describe=True to the dxpy.find_jobs call?

http://autodoc.dnanexus.com/bindings/python/current/dxpy_search.html?highlight=find_jobs#dxpy.bindings.search.find_jobs



_Code quote:_
```Python
job_description = _get_job_description(job_id)
```

**Review by jethror1 — CHANGES_REQUESTED** [review]
> Reviewed 2 of 5 files at r1.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/dx_job_monitor/6)* status: 4 of 5 files reviewed, 2 unresolved discussions (waiting on @JasonLing95)

___
*[`dx_job_monitor.py` line 142 at r1](https://reviewable.io/reviews/eastgenomics/dx_job_monitor/6#-Nl94-Qr7yEORNOOdfwo:-Nl94xNWCE3KKU5QNpTC:bvelrkv) ([raw file](https://github.com/eastgenomics/dx_job_monitor/blob/305ac6023d10d92b9837bb95528fec8757e6c742/dx_job_monitor.py#L142)):*
<details><summary><i>Previously, jethror1 (Jethro Rainford) wrote…</i></summary><blockquote>

instead of doing a query for project name for every project thats had jobs run, why don't we do a single query of dx find projects and then we can just look up the ID in this return dict to get the name? we already have a query outside of here to get all 002 projects, which should have the name in the response so could be passed here
</blockquote></details>

`describe=True` is what I was thinking of to specify to dxpy.find_projects which will return the name in that call

**Review by JasonLing95 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/dx_job_monitor/6)* status: 4 of 5 files reviewed, 2 unresolved discussions (waiting on @jethror1)

___
*[`dx_job_monitor.py` line 142 at r1](https://reviewable.io/reviews/eastgenomics/dx_job_monitor/6#-Nl94-Qr7yEORNOOdfwo:-Nl99kdh3mkL5kB8zvGs:bb7f2mf) ([raw file](https://github.com/eastgenomics/dx_job_monitor/blob/305ac6023d10d92b9837bb95528fec8757e6c742/dx_job_monitor.py#L142)):*
<details><summary><i>Previously, jethror1 (Jethro Rainford) wrote…</i></summary><blockquote>

`describe=True` is what I was thinking of to specify to dxpy.find_projects which will return the name in that call
</blockquote></details>

done
___
*[`dx_job_monitor.py` line 150 at r1](https://reviewable.io/reviews/eastgenomics/dx_job_monitor/6#-Nl94RFt4Q0PZbdPaLcz:-Nl99liVCNYqGE4nXwKm:bo5dhs2) ([raw file](https://github.com/eastgenomics/dx_job_monitor/blob/305ac6023d10d92b9837bb95528fec8757e6c742/dx_job_monitor.py#L150)):*
<details><summary><i>Previously, jethror1 (Jethro Rainford) wrote…</i></summary><blockquote>

again do we need to do this? can't all the details be included in _get_jobs_in_porject() if we specify describe=True to the dxpy.find_jobs call?

http://autodoc.dnanexus.com/bindings/python/current/dxpy_search.html?highlight=find_jobs#dxpy.bindings.search.find_jobs
</blockquote></details>

done
now it takes around 3-4mins to run

**Review by jethror1 — APPROVED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/dx_job_monitor/6)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @JasonLing95)

**Review by jethror1 — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/dx_job_monitor/6)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @JasonLing95)

**Pull request merged**
