### PR TITLE
development branch

### PR DESCRIPTION
**Pull request by JasonLing95**
updated dependencies, docker, logging and readme

---
This change is [Reviewable](https://reviewable.io/reviews/eastgenomics/dx_job_monitor/2)

### CODE REVIEW

**Review by jethror1 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/dx_job_monitor/2)* status: 0 of 5 files reviewed, 3 unresolved discussions (waiting on @JasonLing95 and @jethror1)

___
*[dx_job_monitor.py, line 107 at r1](https://reviewable.io/reviews/eastgenomics/dx_job_monitor/2#-MqEL7_G6dLk0BpS6moP:-MqEL7_G6dLk0BpS6moQ:b-6d5di9) ([raw file](https://github.com/eastgenomics/dx_job_monitor/blob/c415c2bb63feca84bdd2ba79282085fba8b6784d/dx_job_monitor.py#L107)):*
> ```Python
>                     message = (
>                         ':x: The following jobs failed in'
>                         f' {project} - {jobs}'
> ```

for each project where a job has failed, could you include a URL to make it easier to quickly see these jobs?
In DNAnexus the URL for failed job filter looks to be: `platform.dnanexus.com/projects/FpVG0G84X7kzq58g19vF1YJQ/monitor?state.values=failed`

Should be able to just replace the `FpVG0G84X7kzq58g19vF1YJQ` above with each project ID and then we will have a clickable link in egg-alerts
___
*[README.md, line 4 at r1](https://reviewable.io/reviews/eastgenomics/dx_job_monitor/2#-MqELnkQ68LoBX44HjMF:-MqELnkQ68LoBX44HjMG:bfhvryv) ([raw file](https://github.com/eastgenomics/dx_job_monitor/blob/c415c2bb63feca84bdd2ba79282085fba8b6784d/README.md#L4)):*
> ```Markdown
> 
> Checks for jobs run in any 002 project in the last 24hr and sends notifications to Slack.  
> If any jobs have failed in a project, a message will be sent to ```egg-alerts```, and those projects where all jobs completed successfully a message will be sent to ```egg-logs```.
> ```

for inline code highlighting you can just use single backticks, triple are just need for multiline blocks
___
*[README.md, line 32 at r1](https://reviewable.io/reviews/eastgenomics/dx_job_monitor/2#-MqEM6HFAJr1peDIR1vr:-MqEM6HFAJr1peDIR1vs:bz4cr4g) ([raw file](https://github.com/eastgenomics/dx_job_monitor/blob/c415c2bb63feca84bdd2ba79282085fba8b6784d/README.md#L32)):*
> ```Markdown
> ## Automation
> 
> A cron job has been set up to run the script daily at 9am: ```0 9 * * *```
> ```

I wouldn't specify how its been set up since if we changed it on the server then the readme is wrong, just leave it at a daily cron job should be set up, then we will have docs on how things are deployed in confluence

**Comment by JasonLing95** [comment]
___
*[dx_job_monitor.py, line 107 at r1](https://reviewable.io/reviews/eastgenomics/dx_job_monitor/2#-MqEL7_G6dLk0BpS6moP:-MqEg-sc1bCPr83ZCxpb:b380s27) ([raw file](https://github.com/eastgenomics/dx_job_monitor/blob/c415c2bb63feca84bdd2ba79282085fba8b6784d/dx_job_monitor.py#L107)):*
<details><summary><i>Previously, jethror1 wrote…</i></summary><blockquote>

for each project where a job has failed, could you include a URL to make it easier to quickly see these jobs?
In DNAnexus the URL for failed job filter looks to be: `platform.dnanexus.com/projects/FpVG0G84X7kzq58g19vF1YJQ/monitor?state.values=failed`

Should be able to just replace the `FpVG0G84X7kzq58g19vF1YJQ` above with each project ID and then we will have a clickable link in egg-alerts
</blockquote></details>

Added URL into alert output

**Comment by JasonLing95** [comment]
___
*[README.md, line 32 at r1](https://reviewable.io/reviews/eastgenomics/dx_job_monitor/2#-MqEM6HFAJr1peDIR1vr:-MqEgK5E2fixHEciZ4mS:b92b6o0) ([raw file](https://github.com/eastgenomics/dx_job_monitor/blob/c415c2bb63feca84bdd2ba79282085fba8b6784d/README.md#L32)):*
<details><summary><i>Previously, jethror1 wrote…</i></summary><blockquote>

I wouldn't specify how its been set up since if we changed it on the server then the readme is wrong, just leave it at a daily cron job should be set up, then we will have docs on how things are deployed in confluence 
</blockquote></details>

Edited readme

**Comment by JasonLing95** [comment]
___
*[README.md, line 4 at r1](https://reviewable.io/reviews/eastgenomics/dx_job_monitor/2#-MqELnkQ68LoBX44HjMF:-MqEgFziAgR2lC3UP_QX:bc9mkf1) ([raw file](https://github.com/eastgenomics/dx_job_monitor/blob/c415c2bb63feca84bdd2ba79282085fba8b6784d/README.md#L4)):*
<details><summary><i>Previously, jethror1 wrote…</i></summary><blockquote>

for inline code highlighting you can just use single backticks, triple are just need for multiline blocks
</blockquote></details>

Edited backticks

**Review by jethror1 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/dx_job_monitor/2)* status: 0 of 5 files reviewed, 3 unresolved discussions (waiting on @JasonLing95 and @jethror1)

___
*[dx_job_monitor.py, line 112 at r2](https://reviewable.io/reviews/eastgenomics/dx_job_monitor/2#-MqFfUWN1rZDxiWtRyBG:-MqFfUWN1rZDxiWtRyBH:b-61ovkp) ([raw file](https://github.com/eastgenomics/dx_job_monitor/blob/47cb92b08f5e4dd054aaab8a3411d4a3e23e6286/dx_job_monitor.py#L112)):*
> ```Python
>                         'monitor?state.values=failed'
>                     )
>                     post_message_to_slack('egg-alerts', message)
> ```

can you capture the return code / put this in a `try / except` and log it, will help for debugging if slack gets blocked or the api endpoint goes offline
___
*[dx_job_monitor.py, line 148 at r2](https://reviewable.io/reviews/eastgenomics/dx_job_monitor/2#-MqFg-Bp8t1vhrnvnfMH:-MqFg-Bp8t1vhrnvnfMI:br33f71) ([raw file](https://github.com/eastgenomics/dx_job_monitor/blob/47cb92b08f5e4dd054aaab8a3411d4a3e23e6286/dx_job_monitor.py#L148)):*
> ```Python
> 
>     # set token to env
>     dx.set_security_context(dx_security_context)
> ```

if the auth token expires I assume nothing of the errors will end up in the logs? is there a way to check if an auth token is valid and exit with an appropriate error if not?

**Comment by JasonLing95** [comment]
___
*[dx_job_monitor.py, line 112 at r2](https://reviewable.io/reviews/eastgenomics/dx_job_monitor/2#-MqFfUWN1rZDxiWtRyBG:-MqJEjRP1u_VSFvgZdo4:b-paccgb) ([raw file](https://github.com/eastgenomics/dx_job_monitor/blob/47cb92b08f5e4dd054aaab8a3411d4a3e23e6286/dx_job_monitor.py#L112)):*
<details><summary><i>Previously, jethror1 wrote…</i></summary><blockquote>

can you capture the return code / put this in a `try / except` and log it, will help for debugging if slack gets blocked or the api endpoint goes offline
</blockquote></details>

Added a try catch within the post_message function. Logging error code from either server request fail or slack api token error

**Comment by JasonLing95** [comment]
___
*[dx_job_monitor.py, line 148 at r2](https://reviewable.io/reviews/eastgenomics/dx_job_monitor/2#-MqFg-Bp8t1vhrnvnfMH:-MqJKDug8VVNJlgto5WX:bh23mnt) ([raw file](https://github.com/eastgenomics/dx_job_monitor/blob/47cb92b08f5e4dd054aaab8a3411d4a3e23e6286/dx_job_monitor.py#L148)):*
<details><summary><i>Previously, jethror1 wrote…</i></summary><blockquote>

if the auth token expires I assume nothing of the errors will end up in the logs? is there a way to check if an auth token is valid and exit with an appropriate error if not?
</blockquote></details>

Added logging error if dxpy auth failed. Program will stop if dxpy token failed

**Review by jethror1 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/dx_job_monitor/2)* status: 0 of 5 files reviewed, 2 unresolved discussions (waiting on @JasonLing95 and @jethror1)

___
*[dx_job_monitor.py, line 148 at r2](https://reviewable.io/reviews/eastgenomics/dx_job_monitor/2#-MqFg-Bp8t1vhrnvnfMH:-MqJcn_q2pMozl7_BPaS:b-18lq0e) ([raw file](https://github.com/eastgenomics/dx_job_monitor/blob/47cb92b08f5e4dd054aaab8a3411d4a3e23e6286/dx_job_monitor.py#L148)):*
<details><summary><i>Previously, JasonLing95 (Jason) wrote…</i></summary><blockquote>

Added logging error if dxpy auth failed. Program will stop if dxpy token failed
</blockquote></details>

could you have it send a slack notification if the token is invalid and can't log in? Then we know it has expired and to go update it

**Review by JasonLing95 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/dx_job_monitor/2)* status: 0 of 5 files reviewed, 2 unresolved discussions (waiting on @jethror1)

___
*[dx_job_monitor.py, line 148 at r2](https://reviewable.io/reviews/eastgenomics/dx_job_monitor/2#-MqFg-Bp8t1vhrnvnfMH:-MqJkdua-Y6As60NcGlO:b-7yxnxr) ([raw file](https://github.com/eastgenomics/dx_job_monitor/blob/47cb92b08f5e4dd054aaab8a3411d4a3e23e6286/dx_job_monitor.py#L148)):*
<details><summary><i>Previously, jethror1 wrote…</i></summary><blockquote>

could you have it send a slack notification if the token is invalid and can't log in? Then we know it has expired and to go update it
</blockquote></details>

alert message with error code will be sent to #egg-alerts if dxpy token failed

**Review by jethror1 — APPROVED** [review]
> Reviewed 3 of 5 files at r1, 1 of 2 files at r2, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/dx_job_monitor/2)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @JasonLing95)

**Review by jethror1 — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/dx_job_monitor/2)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @JasonLing95)

**Pull request merged**
